services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "${AUTOMATOR_API_PORT:-5000}:${AUTOMATOR_API_PORT:-5000}"
      - "6080-6089:6080-6089"
    restart: unless-stopped
