"""
tests/test_job_unit.py
----------------------
Unit tests for NaverBlogJob (builder pattern + options).
No browser, no Playwright — MockEditor only.
"""

import pytest
from dataclasses import replace

from automator.editor import BlogEditor, PostContent
from automator.job import NaverBlogJob
from automator.options import AccountOption, TitleOption, ContentOption, MetaOption, RunSetting


# ===========================================================================
# MockEditor
# ===========================================================================

class MockEditor(BlogEditor):
    def __init__(self, fail_on: str | None = None) -> None:
        self.actions: list[tuple] = []
        self._fail_on = fail_on

    def _record(self, name: str, *args) -> None:
        if self._fail_on == name:
            raise RuntimeError(f"MockEditor: forced failure on {name!r}")
        self.actions.append((name, *args))

    def open(self)                          -> None: self._record("open")
    def write_title(self, title: str)       -> None: self._record("write_title", title)
    def write_body(self, body: str)         -> None: self._record("write_body", body)
    def upload_image(self, path: str)       -> None: self._record("upload_image", path)
    def set_representative_image(self, idx) -> None: self._record("set_representative_image", idx)
    def move_cursor_to_end(self)            -> None: self._record("move_cursor_to_end")
    def publish(self)                       -> None: self._record("publish")


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture
def account() -> AccountOption:
    return AccountOption(naver_id="test_id", naver_pw="test_pw", blog_id="test_blog")


@pytest.fixture
def base_job(account) -> NaverBlogJob:
    return NaverBlogJob.for_account(account)


@pytest.fixture
def editor() -> MockEditor:
    return MockEditor()


@pytest.fixture
def full_job(account) -> NaverBlogJob:
    # TitleOption uses default preset paths — title is generated by TitleGenerator
    return (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption())
        .with_content(ContentOption(extra_prompt="테스트 본문"))
        .with_meta(MetaOption())
        .with_setting(RunSetting())
    )


@pytest.fixture
def job_with_images(account) -> NaverBlogJob:
    return (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption())
        .with_content(ContentOption(
            preview_images=["a.jpg", "b.jpg"],
            thumbnail_image="thumb.jpg",
            extra_prompt="본문",
        ))
    )


# ===========================================================================
# 1. Builder
# ===========================================================================

@pytest.mark.unit
def test_for_account_returns_job(account):
    assert isinstance(NaverBlogJob.for_account(account), NaverBlogJob)


@pytest.mark.unit
def test_builder_is_immutable(base_job):
    new_job = base_job.with_title(TitleOption())
    assert new_job is not base_job


@pytest.mark.unit
def test_builder_chaining_preserves_account(account):
    job = NaverBlogJob.for_account(account).with_title(TitleOption()).with_content(ContentOption())
    assert job._account is account


@pytest.mark.unit
def test_branch_does_not_pollute_base(base_job):
    branch = base_job.with_setting(RunSetting(post_interval=999))
    assert base_job._setting is None
    assert branch._setting.post_interval == 999


@pytest.mark.unit
def test_two_branches_are_independent(account):
    """두 브랜치의 TitleOption이 서로 독립적임을 검증한다."""
    base  = NaverBlogJob.for_account(account)
    job_a = base.with_title(TitleOption(learning_type="과외"))
    job_b = base.with_title(TitleOption(learning_type="학원"))
    assert job_a._title.learning_type == "과외"
    assert job_b._title.learning_type == "학원"


@pytest.mark.unit
def test_account_write_url(account):
    assert account.write_url == "https://blog.naver.com/test_blog?Redirect=Write&"


@pytest.mark.unit
def test_account_resolved_session_path(account):
    assert account.resolved_session_path == "test_id_session.json"


@pytest.mark.unit
def test_account_custom_session_path():
    acc = AccountOption(naver_id="id", naver_pw="pw", blog_id="blog", session_path="custom.json")
    assert acc.resolved_session_path == "custom.json"


# ===========================================================================
# 2. Validation
# ===========================================================================

@pytest.mark.unit
def test_validate_raises_without_account():
    with pytest.raises(ValueError, match="AccountOption"):
        NaverBlogJob().validate()


@pytest.mark.unit
def test_validate_raises_on_empty_naver_id(account):
    with pytest.raises(ValueError, match="naver_id"):
        NaverBlogJob.for_account(replace(account, naver_id="")).validate()


@pytest.mark.unit
def test_validate_raises_on_empty_naver_pw(account):
    with pytest.raises(ValueError, match="naver_pw"):
        NaverBlogJob.for_account(replace(account, naver_pw="")).validate()


@pytest.mark.unit
def test_validate_raises_on_empty_blog_id(account):
    with pytest.raises(ValueError, match="blog_id"):
        NaverBlogJob.for_account(replace(account, blog_id="")).validate()


@pytest.mark.unit
def test_validate_raises_on_zero_post_count(account):
    with pytest.raises(ValueError, match="post_count"):
        NaverBlogJob.for_account(replace(account, post_count=0)).validate()


@pytest.mark.unit
def test_validate_raises_on_invalid_template(account):
    """
    잘못된 template(토큰 누락)은 validate() 시점에 ValueError를 발생시킨다.
    (구버전의 min_length/max_length 검사를 대체한다 — TitleOption에 해당 필드 없음)
    """
    with pytest.raises(ValueError, match="missing"):
        NaverBlogJob.for_account(account).with_title(
            TitleOption(template="지역+과목+솔트")  # 학습형태 누락
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_zero_paragraph_count(account):
    with pytest.raises(ValueError, match="paragraph_count"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(paragraph_count=0)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_paragraph_length_inversion(account):
    with pytest.raises(ValueError, match="min_paragraph_length"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(min_paragraph_length=10, max_paragraph_length=5)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_tag_count_inversion(account):
    with pytest.raises(ValueError, match="min_tags"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(min_tags=20, max_tags=5)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_backlink_ratio_over_100(account):
    with pytest.raises(ValueError, match="backlink_ratio"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(backlink_ratio=101)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_negative_post_interval(account):
    with pytest.raises(ValueError, match="post_interval"):
        NaverBlogJob.for_account(account).with_setting(
            RunSetting(post_interval=-1)
        ).validate()


@pytest.mark.unit
def test_validate_does_not_call_editor_on_failure(editor):
    try:
        NaverBlogJob().run(editor)
    except ValueError:
        pass
    assert editor.actions == []


# ===========================================================================
# 3. Publish sequence
# ===========================================================================

@pytest.mark.unit
def test_run_returns_true_on_success(full_job, editor):
    assert full_job.run(editor) is True


@pytest.mark.unit
def test_run_opens_editor_first(full_job, editor):
    full_job.run(editor)
    assert editor.actions[0] == ("open",)


@pytest.mark.unit
def test_run_writes_title_before_body(full_job, editor):
    full_job.run(editor)
    names = [a[0] for a in editor.actions]
    assert names.index("write_title") < names.index("write_body")


@pytest.mark.unit
def test_run_publishes_last(full_job, editor):
    full_job.run(editor)
    assert editor.actions[-1] == ("publish",)


@pytest.mark.unit
def test_run_title_is_generated(account, editor):
    """
    TitleGenerator가 생성한 제목이 write_title()에 전달된다.
    제목은 비어 있지 않은 문자열이어야 한다.
    (구버전 test_run_title_from_extra_prompt 대체 —
     extra_prompt로 제목을 직접 지정하는 방식은 삭제됨)
    """
    job = NaverBlogJob.for_account(account).with_title(TitleOption())
    job.run(editor)
    title_calls = [a for a in editor.actions if a[0] == "write_title"]
    assert len(title_calls) == 1
    assert isinstance(title_calls[0][1], str)
    assert len(title_calls[0][1]) > 0


@pytest.mark.unit
def test_run_body_from_extra_prompt(account, editor):
    job = NaverBlogJob.for_account(account).with_content(ContentOption(extra_prompt="생성된 본문"))
    job.run(editor)
    assert ("write_body", "생성된 본문") in editor.actions


@pytest.mark.unit
def test_run_returns_false_when_editor_raises(account):
    assert NaverBlogJob.for_account(account).run(MockEditor(fail_on="open")) is False


# ===========================================================================
# 4. Image upload
# ===========================================================================

@pytest.mark.unit
def test_preview_images_uploaded_in_order(job_with_images, editor):
    job_with_images.run(editor)
    uploaded = [a[1] for a in editor.actions if a[0] == "upload_image"]
    assert uploaded[:2] == ["a.jpg", "b.jpg"]


@pytest.mark.unit
def test_thumbnail_uploaded_last(job_with_images, editor):
    job_with_images.run(editor)
    uploaded = [a[1] for a in editor.actions if a[0] == "upload_image"]
    assert uploaded[-1] == "thumb.jpg"


@pytest.mark.unit
def test_thumbnail_is_representative(job_with_images, editor):
    job_with_images.run(editor)
    rep = [a for a in editor.actions if a[0] == "set_representative_image"]
    assert rep == [("set_representative_image", 2)]


@pytest.mark.unit
def test_cursor_moved_between_images(job_with_images, editor):
    job_with_images.run(editor)
    names   = [a[0] for a in editor.actions]
    ups     = [i for i, n in enumerate(names) if n == "upload_image"]
    cursors = [i for i, n in enumerate(names) if n == "move_cursor_to_end"]
    assert len(cursors) == 2
    assert ups[0] < cursors[0] < ups[1]
    assert ups[1] < cursors[1] < ups[2]


@pytest.mark.unit
def test_no_cursor_before_first_image(job_with_images, editor):
    job_with_images.run(editor)
    names    = [a[0] for a in editor.actions]
    first_up = names.index("upload_image")
    assert all(i > first_up for i, n in enumerate(names) if n == "move_cursor_to_end")


@pytest.mark.unit
def test_no_images_no_upload_calls(base_job, editor):
    base_job.run(editor)
    assert not any(a[0] == "upload_image" for a in editor.actions)


@pytest.mark.unit
def test_no_rep_image_without_thumbnail(account, editor):
    job = (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption())
        .with_content(ContentOption(preview_images=["a.jpg"], extra_prompt="본문"))
    )
    job.run(editor)
    assert not any(a[0] == "set_representative_image" for a in editor.actions)
