"""
tests/test_job_unit.py
----------------------
Unit tests for NaverBlogJob (builder pattern + options).
No browser, no Playwright — MockEditor only.
"""

import pytest
from dataclasses import replace

from automator.editor import BlogEditor, PostContent, PostStep
from automator.job import NaverBlogJob
from automator.options import AccountOption, TitleOption, ContentOption, MetaOption, RunSetting


# ===========================================================================
# MockEditor
# ===========================================================================

class MockEditor(BlogEditor):
    def __init__(self, fail_on: str | None = None) -> None:
        self.actions: list[tuple] = []
        self._fail_on = fail_on

    def _record(self, name: str, *args) -> None:
        if self._fail_on == name:
            raise RuntimeError(f"MockEditor: forced failure on {name!r}")
        self.actions.append((name, *args))

    def open(self)                          -> None: self._record("open")
    def write_title(self, title: str)       -> None: self._record("write_title", title)
    def write_paragraph(self, text: str, newlines: int = 2) -> None: self._record("write_paragraph", text)
    def upload_image(self, path: str)       -> None: self._record("upload_image", path)
    def set_representative_image(self, idx) -> None: self._record("set_representative_image", idx)
    def move_cursor_to_end(self)            -> None: self._record("move_cursor_to_end")
    def publish(self, schedule_at=None)     -> None: self._record("publish", schedule_at)


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture
def account() -> AccountOption:
    return AccountOption(naver_id="test_id", naver_pw="test_pw", blog_id="test_blog")


@pytest.fixture
def base_job(account) -> NaverBlogJob:
    return NaverBlogJob.for_account(account)


@pytest.fixture
def editor() -> MockEditor:
    return MockEditor()


@pytest.fixture
def full_job(account) -> NaverBlogJob:
    # TitleOption uses default preset paths — title is generated by TitleGenerator
    return (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption(fixed_title="테스트 포스트"))
        .with_content(ContentOption())
        .with_meta(MetaOption())
        .with_setting(RunSetting())
    )


@pytest.fixture
def job_with_images(account) -> NaverBlogJob:
    return (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption(fixed_title="테스트 포스트"))
        .with_content(ContentOption(
            preview_images=["a.jpg", "b.jpg"],
            thumbnail_images=["thumb.jpg"],
            layout=["Image 1", "Image 2", "Paragraph 1", "Thumbnail 1",
                    "Paragraph 2"],
            paragraph_prompt="test prompt",  # triggers mock in conftest
        ))
    )


# ===========================================================================
# 1. Builder
# ===========================================================================

@pytest.mark.unit
def test_for_account_returns_job(account):
    assert isinstance(NaverBlogJob.for_account(account), NaverBlogJob)


@pytest.mark.unit
def test_builder_is_immutable(base_job):
    new_job = base_job.with_title(TitleOption(fixed_title="테스트 포스트"))
    assert new_job is not base_job


@pytest.mark.unit
def test_builder_chaining_preserves_account(account):
    job = NaverBlogJob.for_account(account).with_title(TitleOption(fixed_title="테스트 포스트")).with_content(ContentOption())
    assert job._account is account


@pytest.mark.unit
def test_branch_does_not_pollute_base(base_job):
    branch = base_job.with_setting(RunSetting(post_interval=999))
    assert base_job._setting is None
    assert branch._setting.post_interval == 999


@pytest.mark.unit
def test_two_branches_are_independent(account):
    """두 브랜치의 TitleOption 이 서로 독립적임을 검증한다."""
    base  = NaverBlogJob.for_account(account)
    job_a = base.with_title(TitleOption(fixed_title="테스트 과외"))
    job_b = base.with_title(TitleOption(fixed_title="테스트 학원"))
    assert job_a._title.fixed_title == "테스트 과외"
    assert job_b._title.fixed_title == "테스트 학원"


@pytest.mark.unit
def test_account_write_url(account):
    assert account.write_url == "https://blog.naver.com/test_blog?Redirect=Write&"


@pytest.mark.unit
def test_account_resolved_session_path(account):
    assert account.resolved_session_path == "test_id_session.json"


@pytest.mark.unit
def test_account_custom_session_path():
    acc = AccountOption(naver_id="id", naver_pw="pw", blog_id="blog", session_path="custom.json")
    assert acc.resolved_session_path == "custom.json"


# ===========================================================================
# 2. Validation
# ===========================================================================

@pytest.mark.unit
def test_validate_raises_without_account():
    with pytest.raises(ValueError, match="AccountOption"):
        NaverBlogJob().validate()


@pytest.mark.unit
def test_validate_raises_on_empty_naver_id(account):
    with pytest.raises(ValueError, match="naver_id"):
        NaverBlogJob.for_account(replace(account, naver_id="")).validate()


@pytest.mark.unit
def test_validate_raises_on_empty_naver_pw(account):
    with pytest.raises(ValueError, match="naver_pw"):
        NaverBlogJob.for_account(replace(account, naver_pw="")).validate()


@pytest.mark.unit
def test_validate_raises_on_empty_blog_id(account):
    with pytest.raises(ValueError, match="blog_id"):
        NaverBlogJob.for_account(replace(account, blog_id="")).validate()


@pytest.mark.unit
def test_validate_raises_on_invalid_template(account):
    """
    잘못된 template(토큰 누락)은 validate() 시점에 ValueError를 발생시킨다.
    (구버전의 min_length/max_length 검사를 대체한다 — TitleOption에 해당 필드 없음)
    """
    with pytest.raises(ValueError):
        NaverBlogJob.for_account(account).with_title(
            TitleOption(template="no braces at all")  # 토큰 없음
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_unknown_layout_alias(account):
    with pytest.raises(ValueError, match="Unknown layout alias"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(layout=["Unknown 1"])
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_image_alias_out_of_range(account):
    with pytest.raises(ValueError, match="Image 2"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(
                preview_images=["a.jpg"],
                layout=["Image 1", "Image 2"],  # Image 2 but only 1 image
            )
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_paragraph_gap(account):
    with pytest.raises(ValueError, match="contiguous"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(
                layout=["Paragraph 1", "Paragraph 3"],  # gap: missing 2
            )
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_duplicate_alias(account):
    with pytest.raises(ValueError, match="Duplicate"):
        NaverBlogJob.for_account(account).with_content(
            ContentOption(
                preview_images=["a.jpg"],
                layout=["Image 1", "Image 1"],
            )
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_tag_count_inversion(account):
    with pytest.raises(ValueError, match="min_tags"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(min_tags=20, max_tags=5)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_backlink_ratio_over_100(account):
    with pytest.raises(ValueError, match="backlink_ratio"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(backlink_ratio=101)
        ).validate()


@pytest.mark.unit
def test_validate_raises_on_negative_post_interval(account):
    with pytest.raises(ValueError, match="post_interval"):
        NaverBlogJob.for_account(account).with_setting(
            RunSetting(post_interval=-1)
        ).validate()


@pytest.mark.unit
def test_validate_does_not_call_editor_on_failure(editor):
    try:
        NaverBlogJob().run(editor)
    except ValueError:
        pass
    assert editor.actions == []


# ===========================================================================
# 3. Publish sequence
# ===========================================================================

@pytest.mark.unit
def test_run_returns_none_on_success(full_job, editor):
    assert full_job.run(editor) is None


@pytest.mark.unit
def test_run_writes_title_before_body(full_job, editor):
    full_job.run(editor)
    names = [a[0] for a in editor.actions]
    assert names.index("write_title") < names.index("write_paragraph")


@pytest.mark.unit
def test_run_publishes_last(full_job, editor):
    full_job.run(editor)
    assert editor.actions[-1][0] == "publish"


@pytest.mark.unit
def test_run_title_is_generated(account, editor):
    """
    TitleGenerator가 생성한 제목이 write_title()에 전달된다.
    제목은 비어 있지 않은 문자열이어야 한다.
    (구버전 test_run_title_from_extra_prompt 대체 —
     extra_prompt로 제목을 직접 지정하는 방식은 삭제됨)
    """
    job = NaverBlogJob.for_account(account).with_title(TitleOption(fixed_title="테스트 포스트"))
    job.run(editor)
    title_calls = [a for a in editor.actions if a[0] == "write_title"]
    assert len(title_calls) == 1
    assert isinstance(title_calls[0][1], str)
    assert len(title_calls[0][1]) > 0


@pytest.mark.unit
def test_run_body_is_generated(account, editor):
    """
    ContentOption 없이도 run()이 write_paragraph()를 호출한다.
    단락 텍스트는 비어 있지 않은 문자열이어야 한다.
    """
    job = NaverBlogJob.for_account(account).with_content(ContentOption())
    job.run(editor)
    para_calls = [a for a in editor.actions if a[0] == "write_paragraph"]
    assert len(para_calls) >= 1
    assert all(isinstance(a[1], str) and len(a[1]) > 0 for a in para_calls)


@pytest.mark.unit
def test_run_raises_when_editor_raises(account):
    """editor 에러는 삼키지 않고 그대로 전파된다."""
    with pytest.raises(Exception):
        NaverBlogJob.for_account(account).run(MockEditor(fail_on="open"))


# ===========================================================================
# 4. Image upload
# ===========================================================================

@pytest.mark.unit
def test_preview_images_uploaded_in_order(job_with_images, editor):
    job_with_images.run(editor)
    uploaded = [a[1] for a in editor.actions if a[0] == "upload_image"]
    assert uploaded[:2] == ["a.jpg", "b.jpg"]


@pytest.mark.unit
def test_thumbnail_uploaded_last(job_with_images, editor):
    job_with_images.run(editor)
    uploaded = [a[1] for a in editor.actions if a[0] == "upload_image"]
    assert uploaded[-1] == "thumb.jpg"


@pytest.mark.unit
def test_thumbnail_is_representative(job_with_images, editor):
    # layout: ["Image 1","Image 2","Paragraph 1","Thumbnail 1","Paragraph 2"]
    # images added in layout order: a.jpg(0), b.jpg(1), thumb.jpg(2)
    job_with_images.run(editor)
    rep = [a for a in editor.actions if a[0] == "set_representative_image"]
    assert rep == [("set_representative_image", 2)]


@pytest.mark.unit
def test_cursor_moved_before_each_non_first_step(job_with_images, editor):
    # layout: ["Image 1","Image 2","Paragraph 1","Thumbnail 1","Paragraph 2"]
    # step 0 (Image 1)     — no move_cursor_to_end (first step, i=0)
    # step 1 (Image 2)     — move_cursor_to_end (i>0)
    # step 2 (Paragraph 1) — move_cursor_to_end (i>0)
    # step 3 (Thumbnail 1) — move_cursor_to_end (i>0)
    # step 4 (Paragraph 2) — move_cursor_to_end (i>0)
    # total: 4 move_cursor_to_end calls
    job_with_images.run(editor)
    names   = [a[0] for a in editor.actions]
    cursors = [i for i, n in enumerate(names) if n == "move_cursor_to_end"]
    ups     = [i for i, n in enumerate(names) if n == "upload_image"]
    assert len(cursors) == 4
    # every upload after the first must be preceded by a cursor move
    assert all(any(c < u for c in cursors) for u in ups[1:])


@pytest.mark.unit
def test_no_cursor_before_first_step(job_with_images, editor):
    # The very first step (Image 1) must not be preceded by move_cursor_to_end
    job_with_images.run(editor)
    names    = [a[0] for a in editor.actions]
    first_up = names.index("upload_image")
    cursors_before_first = [i for i, n in enumerate(names)
                            if n == "move_cursor_to_end" and i < first_up]
    assert not cursors_before_first


@pytest.mark.unit
def test_layout_order_is_preserved(job_with_images, editor):
    """
    layout: ["Image 1","Image 2","Paragraph 1","Thumbnail 1","Paragraph 2"]
    → 에디터 액션 순서: upload(a.jpg) → upload(b.jpg) → write_paragraph
                        → upload(thumb.jpg) → write_paragraph
    """
    job_with_images.run(editor)
    # Extract only content actions (ignore move_cursor_to_end, open, write_title, publish)
    content_actions = [
        (a[0], a[1]) for a in editor.actions
        if a[0] in ("upload_image", "write_paragraph")
    ]
    # 스텁 텍스트는 고정값이므로 순서와 타입만 검증한다
    assert [a[0] for a in content_actions] == [
        "upload_image", "upload_image", "write_paragraph",
        "upload_image", "write_paragraph",
    ]
    assert content_actions[0][1] == "a.jpg"
    assert content_actions[1][1] == "b.jpg"
    assert content_actions[3][1] == "thumb.jpg"
    assert isinstance(content_actions[2][1], str) and len(content_actions[2][1]) > 5
    assert isinstance(content_actions[4][1], str) and len(content_actions[4][1]) > 5


@pytest.mark.unit
def test_no_rep_image_without_thumbnail(account, editor):
    # No Thumbnail alias in layout → no set_representative_image call
    job = (
        NaverBlogJob
        .for_account(account)
        .with_title(TitleOption(fixed_title="테스트 포스트"))
        .with_content(ContentOption(
            preview_images=["a.jpg"],
            layout=["Image 1", "Paragraph 1"],
        ))
    )
    job.run(editor)
    assert not any(a[0] == "set_representative_image" for a in editor.actions)


# ===========================================================================
# 5. MetaOption — publish schedule validation
# ===========================================================================

from datetime import datetime, timezone, timedelta
from automator.options import KST


# --- helpers ----------------------------------------------------------------

def _future(minutes: int = 60) -> datetime:
    """Return a KST-aware datetime ``minutes`` from now."""
    return datetime.now(tz=KST) + timedelta(minutes=minutes)


def _past(minutes: int = 60) -> datetime:
    """Return a KST-aware datetime ``minutes`` ago."""
    return datetime.now(tz=KST) - timedelta(minutes=minutes)


# --- immediate (default) ----------------------------------------------------

@pytest.mark.unit
def test_meta_immediate_default_passes(account):
    """Default MetaOption() has schedule_mode='immediate' and passes validation."""
    NaverBlogJob.for_account(account).with_meta(MetaOption()).validate()


@pytest.mark.unit
def test_meta_immediate_ignores_schedule_at(account):
    """'immediate' mode ignores schedule_at even when set — no error."""
    NaverBlogJob.for_account(account).with_meta(
        MetaOption(schedule_mode="immediate", schedule_at=_past())
    ).validate()


# --- fixed ------------------------------------------------------------------

@pytest.mark.unit
def test_meta_fixed_future_passes(account):
    """'fixed' mode with a future KST datetime passes validation."""
    NaverBlogJob.for_account(account).with_meta(
        MetaOption(schedule_mode="fixed", schedule_at=_future())
    ).validate()


@pytest.mark.unit
def test_meta_fixed_none_raises(account):
    """'fixed' mode without schedule_at raises ValueError."""
    with pytest.raises(ValueError, match="schedule_at"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(schedule_mode="fixed", schedule_at=None)
        ).validate()


@pytest.mark.unit
def test_meta_fixed_naive_datetime_raises(account):
    """'fixed' mode with a naive (no tzinfo) datetime raises ValueError."""
    naive = datetime(2099, 1, 1, 9, 0)  # no tzinfo
    with pytest.raises(ValueError, match="timezone"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(schedule_mode="fixed", schedule_at=naive)
        ).validate()


@pytest.mark.unit
def test_meta_fixed_past_raises(account):
    """'fixed' mode with a past datetime raises ValueError."""
    with pytest.raises(ValueError, match="미래"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(schedule_mode="fixed", schedule_at=_past())
        ).validate()


# --- random_window ----------------------------------------------------------

@pytest.mark.unit
def test_meta_random_window_future_passes(account):
    """'random_window' mode with future schedule_at and positive jitter passes."""
    NaverBlogJob.for_account(account).with_meta(
        MetaOption(
            schedule_mode="random_window",
            schedule_at=_future(120),
            schedule_jitter_minutes=30,
        )
    ).validate()


@pytest.mark.unit
def test_meta_random_window_none_raises(account):
    """'random_window' mode without schedule_at raises ValueError."""
    with pytest.raises(ValueError, match="schedule_at"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(schedule_mode="random_window", schedule_at=None)
        ).validate()


@pytest.mark.unit
def test_meta_random_window_zero_jitter_raises(account):
    """'random_window' mode with jitter=0 raises ValueError."""
    with pytest.raises(ValueError, match="jitter"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(
                schedule_mode="random_window",
                schedule_at=_future(),
                schedule_jitter_minutes=0,
            )
        ).validate()


@pytest.mark.unit
def test_meta_random_window_negative_jitter_raises(account):
    """'random_window' mode with negative jitter raises ValueError."""
    with pytest.raises(ValueError, match="jitter"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(
                schedule_mode="random_window",
                schedule_at=_future(),
                schedule_jitter_minutes=-10,
            )
        ).validate()


@pytest.mark.unit
def test_meta_random_window_earliest_in_past_raises(account):
    """
    'random_window': schedule_at - jitter가 과거이면 ValueError.
    e.g. schedule_at=지금+10분, jitter=30분 → earliest=지금-20분 (과거)
    """
    with pytest.raises(ValueError, match="미래"):
        NaverBlogJob.for_account(account).with_meta(
            MetaOption(
                schedule_mode="random_window",
                schedule_at=_future(10),   # +10 min from now
                schedule_jitter_minutes=30, # earliest = -20 min → past
            )
        ).validate()


# --- PostContent schedule_at propagation ------------------------------------

@pytest.mark.unit
def test_immediate_produces_none_schedule_at(account, editor):
    """
    'immediate' mode: _generate_content() returns PostContent.schedule_at=None.
    publish() must be called without a schedule argument.
    """
    job = (
        NaverBlogJob.for_account(account)
        .with_meta(MetaOption(schedule_mode="immediate"))
    )
    job.run(editor)
    publish_calls = [a for a in editor.actions if a[0] == "publish"]
    assert len(publish_calls) == 1
    # MockEditor records publish(schedule_at=None) as ("publish", None)
    assert publish_calls[0] == ("publish", None)


@pytest.mark.unit
def test_fixed_schedule_propagated_to_publish(account, editor):
    """
    'fixed' mode: resolved schedule_at is propagated to editor.publish().
    """
    target = _future(120)
    job = (
        NaverBlogJob.for_account(account)
        .with_meta(MetaOption(schedule_mode="fixed", schedule_at=target))
    )
    job.run(editor)
    publish_calls = [a for a in editor.actions if a[0] == "publish"]
    assert len(publish_calls) == 1
    assert publish_calls[0] == ("publish", target)


@pytest.mark.unit
def test_random_window_schedule_within_range(account, editor):
    """
    'random_window' mode: resolved schedule_at must be within
    [schedule_at - jitter, schedule_at + jitter].
    """
    center  = _future(120)
    jitter  = 30
    job = (
        NaverBlogJob.for_account(account)
        .with_meta(MetaOption(
            schedule_mode="random_window",
            schedule_at=center,
            schedule_jitter_minutes=jitter,
        ))
    )
    job.run(editor)
    publish_calls = [a for a in editor.actions if a[0] == "publish"]
    resolved: datetime = publish_calls[0][1]
    assert center - timedelta(minutes=jitter) <= resolved <= center + timedelta(minutes=jitter)
